version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: m1_s3cr3t
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network
    restart: always

volumes:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge
